from app.domain.quiz import (
    CORRECT_POINTS,
    INCORRECT_POINTS,
    QUESTION_DURATION_SECONDS,
    REVEAL_DURATION_SECONDS,
)

PHYSICS_SPRINT_BANK_KEY = "physics-sprint-v1"
FREE_ROOM_MAXIMUM_MEMBERS = 8
ROOM_MAXIMUM_MEMBERS = 20
ROOM_MINIMUM_MEMBERS = 2

__all__ = [
    "CORRECT_POINTS",
    "INCORRECT_POINTS",
    "FREE_ROOM_MAXIMUM_MEMBERS",
    "PHYSICS_SPRINT_BANK_KEY",
    "QUESTION_DURATION_SECONDS",
    "REVEAL_DURATION_SECONDS",
    "ROOM_MAXIMUM_MEMBERS",
    "ROOM_MINIMUM_MEMBERS",
]
